profile: microservice-config-kafka-dev
user.id: 50
user.name: ningquan
user.age: 22
profileConfig: gitcontent
com.zhht.mq.servername: zhht
com.zhht.mq.serverip: 10.110.60.11
com.zhht.mq.password: 123456

