profile: microservice-config-kafka-dev-20180333
user.id: 50
user.name: ningquan
user.age: 22
profileConfig: gitcontent
com.zhht.mq.servername: zhht
com.zhht.mq.serverip: 10.110.60.11
com.zhht.mq.password: 123456
server:
  port: 9800
  context-path: /
  tomcat:
    max-threads: 200
    uri-encoding: UTF-8
    #存放Tomcat的日志、Dump等文件的临时文件夹，默认为系统的tmp文件夹（如：C:\Users\Shanhy\AppData\Local\Temp）
    basedir: D:/data/tomcat8-application/${spring.application.name}/
    max-http-post-size: 10485760
    #打开Tomcat的Access日志，并可以设置日志格式的方法：
    accesslog:
      enabled: true
      pattern: common
    #accesslog目录，默认在basedir/logs
      directory: logs

logging:
   appender: console
   path: D:/data/logs
   pattern:
    level: info
